name: CI
on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install anyio mcp
      - name: Smoke via STDIO
        env:
          PORT_HUNTER_TOKEN: TEST_TOKEN
          PORT_HUNTER_ALLOWED_DIR: ${{ github.workspace }}
        run: |
          python - << 'PY'
          import json, asyncio
          from mcp.client.stdio import stdio_client
          from mcp.client.session import ClientSession
          async def main():
              async with stdio_client({"command":"python","args":["-m","porthunter.server"]}) as (r,w):
                  async with ClientSession(r,w) as s:
                      await s.initialize()
                      res = await s.call_tool("get_info", {"auth_token":"TEST_TOKEN"})
                      print(json.dumps(res.result))
          asyncio.run(main())
          PY

  tests:
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install anyio mcp pytest
      - name: Run pytest
        env:
          PORT_HUNTER_TOKEN: TEST_TOKEN
          PORT_HUNTER_ALLOWED_DIR: ${{ github.workspace }}
        run: pytest -q
